services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - ticket_net

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket_queue
    working_dir: /var/www
    command: php artisan queue:work --sleep=1 --tries=3 --timeout=120
    volumes:
      - ./:/var/www
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - ticket_net

  nginx:
    image: nginx:1.27-alpine
    container_name: ticket_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - ticket_net

  postgres:
    image: postgres:16-alpine
    container_name: ticket_postgres
    environment:
      POSTGRES_DB: tickets
      POSTGRES_USER: tickets_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tickets_user -d tickets"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - ticket_net

  redis:
    image: redis:7-alpine
    container_name: ticket_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - ticket_net

volumes:
  postgres_data:
  redis_data:

networks:
  ticket_net:
    driver: bridge
